name: weather_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl:
  dio:
  flutter_typeahead:
  geolocator:
  provider:
  flutter_native_splash:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"
flutter_native_splash:
  android: true
  ios: true
  fullscreen: true
  background_image: "assets/images/bg_launcher.png"
  image: assets/images/launcher_icon.png
  android_12:
    image: assets/images/launcher_icon_rounded.png
    color: "#673AB7"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
